### ISSUE TITLE
Deprecation Issue on Atom v1.13.0

### ISSUE THREAD

**Issue by bhgomes** [fredoliveira/string-theory#2]
Using this theme on recent Atom versions causes a deprecation call because of the removal of the shadow DOM boundary. If anyone is still working on this project it would be very much appreciated if this were resolved. It is a relatively trivial fix.

**Comment by fredoliveira** [comment]
Just published a new version, thanks to the work of @evnpwr fixing the deprecated selectors. Check for updates in Atom and update to `0.1.3` :-)
